name: radon_plugin
version: 0.0.1
language: 
description: A python anlayzer to check python files quality
tags:
 - python
 - radon
 - format
 - analyzer
 - quality
 - plugin

public: true

# clone_in_docker: false

outputs:
  - name: FLOW_RADON_CC_LOG_PATH
  - name: FLOW_RADON_RAW_LOG_PATH
  - name: FLOW_RADON_MI_LOG_PATH
  - name: FLOW_FILE_RADON_CC_FILE_COUNT
  - name: FLOW_FILE_RADON_CC_WARN_COUNT
  
script_path: ./run.sh
